Repository Cutting-Edge-Developers/code-ve-ceza, pull requests merged in 2022-07, with the labels that each got.

#3 Revert code & added some feat
  .gitignore
  README.md
  index.html
  src/css/components/brands.css
  src/js/main.js
Labels: bug, ✨feature

#15 Added Button Component
  index.html
  src/css/components/buttons.css
  src/css/components/header.css
Labels: ✨feature

#16 Added collection component & container class
  index.html
  src/css/components/collections.css
  src/css/helper.css
  src/js/components/buttons.js
  src/js/components/footer.js
  src/js/main.js
  src/static/ETH.svg
  src/static/collection_item_image/01Otherdeed-for-Otherside.jpg
  src/static/collection_item_image/02-Otherdeed-for-Otherside.png
  src/static/collection_item_image/03-Bored-Ape-Yacht-Club.png
  src/static/collection_item_image/04-God-Hates-NFTees.jpg
  src/static/collection_item_image/05-Moonbirds.png
  src/static/collection_item_image/06-mutant-ape-yacht-club.png
  src/static/collection_item_image/07-degens-town.gif
  src/static/collection_item_image/08-art-blocks-curated.png
  src/static/collection_item_image/09-cryptopunks.png
  src/static/collection_item_image/10-royal-oak-foundation.png
  src/static/collection_item_image/11-clonex.png
  src/static/collection_item_image/12-murakami-flowers-2022-official.png
  src/static/collection_item_image/13-copebears.jpg
  src/static/collection_item_image/14-doodles-official.jpg
  src/static/collection_item_image/15-good-minds-nft.png
Labels: ✨feature

#20 Added Notable Drop Component
  index.html
  src/css/components/notableDrops.css
  src/js/components/sliders.js
  src/js/main.js
  src/static/notabledrops-image/01-seeinggreen-promocard.jpg
  src/static/notabledrops-image/02-serenescapes-promocard.jpg
  src/static/notabledrops-image/03-blindgeometric-promocard.jpg
  src/static/notabledrops-image/04-Homepage-OuterversePassport.jpg
  src/static/notabledrops-image/05-Hume_Genesis_OpenSea_Notable-Banner_1125x1740.jpg
  src/static/notabledrops-image/06-kingship-promocard.jpg
  src/static/notabledrops-image/07-oddities-openSea-featured.png
Labels: ✨feature

#19 Added Footer Component
  index.html
  src/css/components/footer.css
Labels: conflict, Resolve Conflict

#23 Brands Section Added
  index.html
  src/css/components/brands.css
  src/css/helper.css
  src/js/components/brands.js
  src/js/main.js
  src/static/brands/1.svg
  src/static/brands/2.svg
  src/static/brands/3.svg
  src/static/brands/4.svg
  src/static/brands/5.svg
  src/static/brands/6.svg
Labels: conflict, Resolve Conflict
