Repository Cutting-Edge-Developers/code-ve-ceza, pull requests merged in 2022-08, with the labels that each got.

#26 Completed the meet section
  index.html
  src/css/components/meetSection.css
  src/static/meet-section/video-background.svg
Labels: conflict, Resolve Conflict

#28 Hero section completed except responsive breakpoints yet
  index.html
  src/css/components/footer.css
  src/css/components/heroSection.css
  src/static/hero_section_assets/hero_learn_more_icon.svg
  src/static/hero_section_assets/hero_section_nft_image.gif
  src/static/hero_section_assets/hero_section_nft_image_2.jpg
  src/static/hero_section_assets/learn_more_link_icon.png
  src/static/hero_section_assets/small_icon_of_the_nft_artist_.png
Labels: ✨feature

#30 completed hero-section and responsive design
  src/css/components/heroSection.css
Labels: ✨feature

#33 footer.css bitti
  src/css/components/footer.css
Labels: bug, ✨feature

#39 fix(footer.css):changed some classNames
  src/css/components/footer.css
Labels: bug
